### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by baonguyen010599** [phannguyenminhphat1/CNPMNCC#7]
Dành cho actor admin, giao viên,học sinh
Validation : Báo rỗng , không cho phép các kí tự đặc biệt
Đăng nhập bằng username, password
Admin:
 _ Sau khi đăng nhập vào trang quản trị
Giao viên 
_ Sau khi đăng  nhập vào trang quản lí câu hỏi
Học sinh:
_Sau khi đăng nhập vào trang thi

**Comment by luupnh** [comment]
Thiết kế giao diện đăng nhập chung cho cả giảng viên (quản trị viên) và học sinh
